build site:
  image: node:10.16
  stage: build
  script:
    - npm install --progress=false
    - npm run build-storybook
  artifacts:
    expire_in: 1 week
    paths:
      - storybook-static
  tags:
    - docker

# unit test:
#   image: node:10.16
#   stage: test
#   script:
#     - npm install --progress=false
#     - npm run test:unit
#   tags:
#     - docker

# PAGES aren't implemented at this point.
# pages: # the job must be named pages
#   image: node:latest
#   stage: deploy
#   script:
#     - npm ci
#     - npm run build-storybook
#     - mv public public-vue # GitLab Pages hooks on the public folder
#     - mv storybook-static public # rename the dist folder (result of npm run build)
#   artifacts:
#     paths:
#       - public # artifact path must be /public for GitLab Pages to pick it up
#   only:
#     - master